---
roles:
  - name: gantsign.visual-studio-code
  - name: jan_matthis.julia
  - name: agucova.asdf
    src: git+https://github.com/agucova/ansible-asdf.git
collections:
  - name: community.general
  - name: crivetimihai.virtualization
