- hosts: localhost
  become: true

  vars:
    user: agucova
    github_user: agucova
    repo_name: workspace
    cache_dir: /var/cache/ansible
    python_latest_version: 3.9.5
    wolfram_email: agucova@uc.cl

  vars_prompt:
    - name: mathematica_lic_key
      prompt: "What is your Mathematica License Key? (no dash, skipped if empty)"

  pre_tasks:
    - include: tasks/cache.yml
    - include: tasks/directories.yml
    - include: tasks/dotfiles.yml
    - include: tasks/gnome.yml
    - include: tasks/zoom.yml
    - include: tasks/firefox-dev.yml

  roles:
    - role: gantsign.visual-studio-code
    - role: jan_matthis.julia
      julia_symlink_dir: /usr/local
      julia_dir: /opt/julia
    - role: crivetimihai.virtualization.kvm
    - role: crivetimihai.virtualization.podman
    - role: crivetimihai.virtualization.docker

  tasks:
    - include: tasks/packages.yml
    - include: tasks/mathematica.yml
    - include: tasks/discord.yml
    - include: tasks/python.yml
    - include: tasks/rust.yml

  handlers:
  - name: Update desktop files
    command: update-desktop-database ~/.local/share/applications -v

  - name: Reload font cache
    file: src=/home/linuxbrew/.linuxbrew/share/fonts dest=/home/{{ user }}/.local/share/fonts state=link
