- name: Download Discord
  get_url: url=https://discordapp.com/api/download?platform=linux&format=deb dest={{ cache_dir }}/discord.deb

- name: Install Discord
  become: true
  apt: deb={{ cache_dir }}/discord.deb state=present
