- name: Install pyenv versions
  command:
    cmd: "/home/linuxbrew/.linuxbrew/bin/pyenv install -s {{ item }}"
    creates: "/home/{{ user }}/.pyenv/versions/{{ item }}/"
  with_items:
    - "{{ python_latest_version }}"
    - 3.8.11
  become: true
  become_user: "{{ user }}"

- name: Check global python version
  shell: "cat /home/{{ user }}/.pyenv/version | echo ''"
  become: true
  become_user: "{{ user }}"
  register: python_global_version
  changed_when: false
        


- name: "Set Python version {{ python_latest_version }} as global"
  command:
    cmd: "/home/linuxbrew/.linuxbrew/bin/pyenv global {{ python_latest_version }}"
  become: true
  become_user: "{{ user }}"
  environment:
    PATH: "/home/linuxbrew/.linuxbrew/bin/pyenv:{{ ansible_env.PATH }}"
  when: python_global_version.stdout != python_latest_version

- name: Download Poetry
  get_url: url=https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py dest={{ cache_dir }}/get-poetry.py

- name: Install Poetry
  command:
    cmd: "/usr/bin/python3 {{ cache_dir }}/get-poetry.py -y"
    creates: "/home/{{ user }}/.poetry/bin/poetry"
  become_user: "{{ user }}"
  become: true

