# Key fingerprint: 3960 60CA DD8A 7522 0BFC B369 B903 BF18 61A7 C71D
- name: Download Zoom
  get_url: url=https://zoom.us/client/latest/zoom_amd64.deb
           dest={{cache_dir}}/zoom_amd64.deb

- name: Install Zoom
  become: true
  apt: deb={{cache_dir}}/zoom_amd64.deb
       state=present
