- name: Create ~/repos/
  file:
    path: "/home/{{ user }}/repos"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0770

- name: Create ~/.bin/
  file:
    path: "/home/{{ user }}/.bin"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0770

- name: Create ~/.local/share/fonts/
  file:
    path: /home/{{ user }}/.local/share/fonts/
    state: directory
  notify:
    - Reload font cache
