- name: Install Rust
  ansible.builtin.shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  args:
    creates: "/home/{{ user }}/.cargo/bin/rustup"
  become: true
  become_user: "{{ user }}"
